# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventmaps', to=settings.AUTH_USER_MODEL),
        ),
    ]
