# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20170228_0720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='layer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
